services:
  node1:
    build: .
    platform: linux/amd64
    container_name: node1
    ports:
      - "3001:3000"
    environment:
      - NODE_ID=1
    command: sh -c "zig build && ./zig-out/bin/chapter7 --listen 3000"

  node2:
    build: .
    platform: linux/amd64
    container_name: node2
    ports:
      - "3002:3000"
    environment:
      - NODE_ID=2
    command: sh -c "zig build && ./zig-out/bin/chapter7 --listen 3000 --connect node1:3000"

  node3:
    build: .
    platform: linux/amd64
    container_name: node3
    ports:
      - "3003:3000"
    environment:
      - NODE_ID=3
    command: sh -c "zig build && ./zig-out/bin/chapter7 --listen 3000 --connect node1:3000"
