name: Zig CI

on:
  push: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Build
      run: zig build

    - name: Run tests
      run: zig build test

    - name: Run program
      run: zig build run
